# Indentation
tab_spaces = 4

# Keep string formatting consistent
format_strings = true

# Maintain spaces around range expressions
spaces_around_ranges = true

# Imports
reorder_imports = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Docs
wrap_comments = true
comment_width = 100
normalize_comments = true
format_code_in_doc_comments = true
